@startsalt " Edit Work Item"

    {+
        == Edit Work Item (33.5 Hours)
        ---
        {
            {
                "Work Item Title"
                Description 
                {SI 
                    Description of my work title here. 
                    .
                    .
                    .
                }
                {
                    Component | "E-Signatures Web Service"
                    Tags | "mvp,use case"
                    Confidence % | "85"
                    Resource | "John"
                    ...
                    [] De-scoped (Not calculated)
                }
                ---
                {^"Time"
                    Calculation Template: | ^Basic ^Basic ^Test Intensive ^Research Intensive^  | [Re-calculate]
                    {^"Calculated Fields"
                        Development | "10"
                        Research | "12.5"
                        Testing | "10"
                        Code Review | "1.5"
                    }
                    {^"Additional Fields"
                        Deployment | "12.5"
                        Data Entry | "10"
                    } | [Add] | [Remove]
                }
                
            }
            {+
                [Save] | [Cancel]
            }
        }
    }
@endsalt