@startsalt "Edit Component"

    {+
        == Edit Component
        ---
        {
            {
                "Component Title"
                Description 
                {SI 
                    Description of my component here. 
                    .
                    .
                    .
                }
                {
                    Tags | "mvp,use case"
                    [] De-scoped (Not calculated)
                }
                ---
            }
            {+
                [Save] | [Cancel]
            }
        }
    }
@endsalt