@startsalt "Manage Components"

    {+
        == Manage Components
        {+
            {/ Overview | Work Items | Resources | <b>Components }
        }
        ---
        {+
            ---
            {
                Include Tags: | "in-scope,mvp" | Exclude Tags: | "in-scope,mvp" | 
            }
            ---
            {S
                {T#
                    +E-Signatures Web Service | Descoped | Tags
                    +Web Client UI | Yes | mvp,ui,
                    +BFF Layer | - | backend,mvp,todo
                    +Billing Service | - | backend
                    +Prepare Billing Azure Function | - | mvp,azure,
                    +B2C Fixes | - | security
                }
            }

            {+
                [Add] | [Edit] | [Delete] | [Close]
            }
        }

        {+
            [Close]
        }
    }
@endsalt