@startsalt "New Component"

    {+
        == New Component
        ---
        {
            {
                Name: | "Component Title"
                Tags | "mvp,use case"
            }
            {+
                [Save] | [Cancel]
            }
        }
    }
@endsalt