@startsalt "Edit Resource"

    {+
        == Edit Resource
        ---
        {
            {
                {
                    Resource: | "Tom Banks"
                    Currency: | ^Rand^
                    Cost: | "250.10"
                }
                ---
            }
            {+
                [Save] | [Cancel]
            }
        }
    }
@endsalt