@startsalt "Dashboard"

{+
    == Dashboard
    ---
    {+
        {/ <b>Overview | Work Items | Resources | Components | Settings }
    }
    {
    }
    {
        Confidence | 75%
        Include Tags: | "in-scope,mvp" | Exclude Tags: | "in-scope,mvp" | 
    }
    ...
    <b>Duration
    Days Estimated: <b>210
    Start Date: Tues 12 Jan 2022
    End Date: Wed 13 Aug 2022
    ...
    {
        <b>Monetary Cost
        Currency | ^Dollars^
    }

    ...
    {T#
        +<b>Component | <b>Best Case | <b>Worst Case | <b>Estimated Case
        + NamesService  | $3345.23 | $3345.23 | $3345.23
        + NamesWebclient   | $3345.23 | $3345.23 | $3345.23
        +<b>Total | <b>$3345.23 | <b>$3345.23 | <b>$3345.23
    }
    ...
    {
        <b>Hours Estimated: <b>34
        Enter Estimation Units | ^days ^days ^hours^
    }
    ...
    {T#
        +<b>Component | <b>Best Case | <b>Worst Case | <b>Estimated Case
        + NamesService  | 12 | 18 | 16
        + NamesWebclient   | 14 | 22 | 18
        +<b>Total | <b>26 | <b>32 | <b>34
    }
    ...
    {T#
        +<b>Resource | <b>Best Case | <b>Worst Case | <b>Estimated Case
        + John  | 12 | 18 | 16
        + Paul   | 14 | 22 | 18
        + Alice   | 14 | 22 | 18
    }
    ...

    {+
        [Close]
    }
}

@endsalt