@startsalt

    {+
        == Manage Tags
        {+
            {/ Overview | Work Items | Tags | Resources | <b>Components }
        }
        ---
        {+
            {SI
                mvp
                todo
                done
                requires-input
                awaiting-business
            }
            {+
                [Add] | [Edit] | [Delete] | [Close]
            }
        }

        {+
            [Close]
        }
    }
@endsalt