@startuml "New/Edit Custom Estimate Ratio"
    left to right direction

    actor  "User" as user

    rectangle "System" {
        usecase "New Custom Edit Ratio" as new
        usecase "Update Custom Edit Ratio" as update
        usecase "Get Custom Edit Ratio" as get
    }

    user -- new
    user -- update

    user -- get

@enduml