@startuml
    ' https://plantuml.com/salt

    class Component {}
    class WorkItem {
        Title
        Tags
        ConfidencePercentage
        EstimatedHours
        Reset(CalculationTemplate)
    }
    class TimeEstimate {
        Title
        Value:TimeSpan
    }
    class RelativeTimeEstimate {
        Ratio
        BasedOnEstimate: TimeEstimate
    }
    class Resource {}
    class Tag {}
    class CalculationTemplate {}

    Component -- Tag
    WorkItem -- Tag
    TimeEstimate <|-- RelativeTimeEstimate

    WorkItem -- Component
    WorkItem -- Resource
    WorkItem -- TimeEstimate

    CalculationTemplate -- RelativeTimeEstimate

@enduml