@startuml
    ' https://plantuml.com/salt

    class Component {}
    class WorkItem {}
    class Resource {}
    class Tag {}
    class Estimate {}
    class CalculationTemplate {}
    class ConfidenceLevel {}
    class EstimateRatio {}

    Component -- Tag
    WorkItem -- Estimate
    WorkItem -- Tag
    Estimate -- EstimateRatio



    WorkItem -- Component
    WorkItem -- CalculationTemplate
    WorkItem -- Resource
    WorkItem -- ConfidenceLevel

@enduml